// import { EventData, NoticeData, PartyReportData, UserReportData } from '@/types/userReport';

// export const allEvents: EventData[] = [
//    {
//       name: '봄맞이 꽃 축제',
//       host: '서울시',
//       period: '2025-03-01 ~ 2025-03-31',
//       operating_hours: '09:00 ~ 18:00',
//       price: '무료',
//       location: '여의도 공원',
//       state: '진행중',
//    },
//    {
//       name: '여름 음악 페스티벌',
//       host: '문화재단',
//       period: '2025-07-15 ~ 2025-07-17',
//       operating_hours: '14:00 ~ 22:00',
//       price: '50,000원',
//       location: '올림픽공원',
//       state: '예정',
//    },
//    {
//       name: '가을 푸드 트럭 축제',
//       host: '강남구청',
//       period: '2025-09-10 ~ 2025-09-12',
//       operating_hours: '11:00 ~ 20:00',
//       price: '무료',
//       location: '코엑스 광장',
//       state: '예정',
//    },
//    {
//       name: '겨울 빛 축제',
//       host: '관광공사',
//       period: '2024-12-01 ~ 2024-12-31',
//       operating_hours: '17:00 ~ 23:00',
//       price: '15,000원',
//       location: '청계천',
//       state: '종료',
//    },
//    {
//       name: '크리스마스 마켓',
//       host: '명동상인회',
//       period: '2024-12-15 ~ 2024-12-25',
//       operating_hours: '10:00 ~ 22:00',
//       price: '무료',
//       location: '명동 거리',
//       state: '취소',
//    },
//    {
//       name: '한강 불꽃축제',
//       host: '서울시',
//       period: '2025-10-05 ~ 2025-10-05',
//       operating_hours: '19:00 ~ 21:00',
//       price: '무료',
//       location: '여의도 한강공원',
//       state: '예정',
//    },
//    {
//       name: '서울 재즈 페스티벌',
//       host: '문화재단',
//       period: '2025-05-20 ~ 2025-05-22',
//       operating_hours: '16:00 ~ 22:00',
//       price: '80,000원',
//       location: '올림픽공원',
//       state: '예정',
//    },
//    {
//       name: '서울 국제 영화제',
//       host: '영화진흥위원회',
//       period: '2025-10-01 ~ 2025-10-10',
//       operating_hours: '10:00 ~ 22:00',
//       price: '12,000원',
//       location: '광화문 시네마',
//       state: '예정',
//    },
//    {
//       name: '강남 페스티벌',
//       host: '강남구청',
//       period: '2025-08-15 ~ 2025-08-17',
//       operating_hours: '12:00 ~ 21:00',
//       price: '무료',
//       location: '강남역 광장',
//       state: '예정',
//    },
//    {
//       name: '한강 마라톤 대회',
//       host: '마라톤협회',
//       period: '2025-04-20 ~ 2025-04-20',
//       operating_hours: '06:00 ~ 12:00',
//       price: '30,000원',
//       location: '반포 한강공원',
//       state: '예정',
//    },
//    {
//       name: '서울 빛초롱 축제',
//       host: '종로구청',
//       period: '2025-11-01 ~ 2025-11-30',
//       operating_hours: '18:00 ~ 23:00',
//       price: '무료',
//       location: '청계천 일대',
//       state: '예정',
//    },
//    {
//       name: '전통주 페스티벌',
//       host: '농림축산식품부',
//       period: '2025-09-25 ~ 2025-09-27',
//       operating_hours: '13:00 ~ 20:00',
//       price: '20,000원',
//       location: 'DDP',
//       state: '예정',
//    },
// ];

// export const allNotices: NoticeData[] = [
//    {
//       name: '[공지] 2025년 설날 연휴 운영 안내',
//       add_date: '2025-01-15',
//       edit_date: '2025-01-16',
//       top_fixed: true,
//       category: '일반',
//    },
//    {
//       name: '[업데이트] 새로운 기능이 추가되었습니다',
//       add_date: '2025-01-10',
//       edit_date: '2025-01-12',
//       top_fixed: true,
//       category: '업데이트',
//    },
//    {
//       name: '[이벤트] 신규 회원 가입 이벤트 진행중',
//       add_date: '2025-01-08',
//       edit_date: '2025-01-08',
//       top_fixed: false,
//       category: '이벤트',
//    },
//    {
//       name: '[정책] 개인정보 처리방침 변경 안내',
//       add_date: '2025-01-05',
//       edit_date: '2025-01-07',
//       top_fixed: false,
//       category: '이용정책',
//    },
//    {
//       name: '[공지] 서비스 점검 안내 (1월 20일)',
//       add_date: '2025-01-03',
//       edit_date: '2025-01-03',
//       top_fixed: false,
//       category: '일반',
//    },
//    {
//       name: '[업데이트] 모바일 앱 버전 2.5.0 업데이트',
//       add_date: '2024-12-28',
//       edit_date: '2024-12-30',
//       top_fixed: false,
//       category: '업데이트',
//    },
//    {
//       name: '[이벤트] 연말 감사 프로모션 안내',
//       add_date: '2024-12-20',
//       edit_date: '2024-12-20',
//       top_fixed: false,
//       category: '이벤트',
//    },
//    {
//       name: '[공지] 고객센터 운영시간 변경 안내',
//       add_date: '2024-12-15',
//       edit_date: '2024-12-18',
//       top_fixed: false,
//       category: '일반',
//    },
//    {
//       name: '[정책] 서비스 이용약관 개정 안내',
//       add_date: '2024-12-10',
//       edit_date: '2024-12-10',
//       top_fixed: false,
//       category: '이용정책',
//    },
//    {
//       name: '[업데이트] 새로운 결제 시스템 도입 안내',
//       add_date: '2024-12-05',
//       edit_date: '2024-12-06',
//       top_fixed: false,
//       category: '업데이트',
//    },
//    {
//       name: '[기타] 파트너사 제휴 안내',
//       add_date: '2024-12-01',
//       edit_date: '2024-12-01',
//       top_fixed: false,
//       category: '기타',
//    },
//    {
//       name: '[공지] 시스템 보안 강화 작업 완료',
//       add_date: '2024-11-25',
//       edit_date: '2024-11-27',
//       top_fixed: false,
//       category: '일반',
//    },
// ];

// export const allUserReports: UserReportData[] = [
//    {
//       user_name: '김철수',
//       phone_number: '010-1234-5678',
//       reporter_name: '이영희',
//       event_name: '봄맞이 꽃 축제',
//       report_date: '2025-01-15',
//       report_category: '부정적인 언어',
//       sanction_content: '다른 참가자에게 욕설 및 비방 발언을 하였습니다.',
//       sanction_type: '7일 계정정지',
//       sanction_period: '2025-01-15 ~ 2025-01-22',
//       sanction_chat: '김철수: 너 정말 최악이야\n김철수: 이런 이벤트에 왜 왔어?',
//       add_opinion: '이 사용자는 이전에도 여러 번 비슷한 행동을 반복했습니다. 엄중한 조치 부탁드립니다.',
//       is_processed: true,
//    },
//    {
//       user_name: '박민수',
//       phone_number: '010-2345-6789',
//       reporter_name: '최지현',
//       event_name: '여름 음악 페스티벌',
//       report_date: '2025-01-14',
//       report_category: '도배',
//       sanction_content: '채팅창에 동일한 메시지를 30회 이상 반복 전송했습니다.',
//       sanction_type: '7일 계정정지',
//       sanction_period: '2025-01-14 ~ 2025-01-21',
//       sanction_chat: '박민수: 할인 쿠폰 받으세요\n박민수: 할인 쿠폰 받으세요\n박민수: 할인 쿠폰 받으세요\n(30회 반복)',
//       add_opinion: '채팅이 너무 많아서 정상적인 대화가 불가능했습니다.',
//       is_processed: true,
//    },
//    {
//       user_name: '정수진',
//       phone_number: '010-3456-7890',
//       reporter_name: '강민호',
//       event_name: '가을 푸드 트럭 축제',
//       report_date: '2025-01-13',
//       report_category: '광고',
//       sanction_content: '상업적 광고 링크를 지속적으로 게시했습니다.',
//       sanction_type: '미정',
//       sanction_period: '-',
//       sanction_chat: '정수진: 여기서 제품 구매하세요 www.example.com\n정수진: 50% 할인 중입니다',
//       add_opinion: '경고를 했지만 계속 광고를 올려서 신고합니다.',
//       is_processed: false,
//    },
//    {
//       user_name: '홍길동',
//       phone_number: '010-4567-8901',
//       reporter_name: '윤서연',
//       event_name: '겨울 빛 축제',
//       report_date: '2025-01-12',
//       report_category: '사기',
//       sanction_content: '가짜 경품 이벤트로 개인정보를 수집하려 했습니다.',
//       sanction_type: '7일 계정정지',
//       sanction_period: '2025-01-12 ~ 2025-01-19',
//       sanction_chat: '홍길동: 경품 당첨됐어요! 개인정보 알려주세요\n홍길동: 계좌번호와 주민번호 보내주세요',
//       add_opinion: '명백한 사기 행위입니다. 다른 피해자도 있을 것 같습니다.',
//       is_processed: true,
//    },
//    {
//       user_name: '이동욱',
//       phone_number: '010-5678-9012',
//       reporter_name: '김나연',
//       event_name: '크리스마스 마켓',
//       report_date: '2025-01-11',
//       report_category: '기타',
//       sanction_content: '이벤트와 무관한 정치적 발언을 지속했습니다.',
//       sanction_type: '미정',
//       sanction_period: '-',
//       sanction_chat: '이동욱: 정치 이야기 좀 합시다\n이동욱: 여러분은 어느 정당 지지하세요?',
//       add_opinion: '이벤트 분위기를 해쳤습니다.',
//       is_processed: false,
//    },
//    {
//       user_name: '최준호',
//       phone_number: '010-6789-0123',
//       reporter_name: '박서준',
//       event_name: '한강 불꽃축제',
//       report_date: '2025-01-10',
//       report_category: '부정적인 언어',
//       sanction_content: '특정 지역 사람들을 비하하는 발언을 했습니다.',
//       sanction_type: '7일 계정정지',
//       sanction_period: '2025-01-10 ~ 2025-01-17',
//       sanction_chat: '최준호: 그 지역 사람들은 다 그래\n최준호: 민도가 낮아서 그런 거야',
//       add_opinion: '지역 차별 발언으로 매우 불쾌했습니다.',
//       is_processed: true,
//    },
//    {
//       user_name: '강다은',
//       phone_number: '010-7890-1234',
//       reporter_name: '정하늘',
//       event_name: '서울 재즈 페스티벌',
//       report_date: '2025-01-09',
//       report_category: '도배',
//       sanction_content: '이모티콘을 50회 이상 연속으로 전송했습니다.',
//       sanction_type: '미정',
//       sanction_period: '-',
//       sanction_chat: '강다은: 😀😀😀😀😀\n강다은: 😀😀😀😀😀\n(50회 반복)',
//       add_opinion: '',
//       is_processed: false,
//    },
//    {
//       user_name: '신예은',
//       phone_number: '010-8901-2345',
//       reporter_name: '조민수',
//       event_name: '서울 국제 영화제',
//       report_date: '2025-01-08',
//       report_category: '광고',
//       sanction_content: '타 플랫폼 홍보 메시지를 반복적으로 게시했습니다.',
//       sanction_type: '7일 계정정지',
//       sanction_period: '2025-01-08 ~ 2025-01-15',
//       sanction_chat: '신예은: 제 유튜브 채널 구독하세요\n신예은: 인스타그램 팔로우 해주세요',
//       add_opinion: '경고했는데도 계속 홍보 메시지를 올렸습니다.',
//       is_processed: true,
//    },
//    {
//       user_name: '한지우',
//       phone_number: '010-9012-3456',
//       reporter_name: '송유진',
//       event_name: '강남 페스티벌',
//       report_date: '2025-01-07',
//       report_category: '사기',
//       sanction_content: '중고거래 사칭으로 금전 요구를 했습니다.',
//       sanction_type: '미정',
//       sanction_period: '-',
//       sanction_chat: '한지우: 티켓 팔아요 50% 할인\n한지우: 계좌로 먼저 입금하시면 보내드릴게요',
//       add_opinion: '이미 피해를 입은 사람이 있다고 들었습니다.',
//       is_processed: false,
//    },
//    {
//       user_name: '오세훈',
//       phone_number: '010-0123-4567',
//       reporter_name: '임채원',
//       event_name: '한강 마라톤 대회',
//       report_date: '2025-01-06',
//       report_category: '부정적인 언어',
//       sanction_content: '성희롱성 발언으로 다른 참가자를 불쾌하게 했습니다.',
//       sanction_type: '7일 계정정지',
//       sanction_period: '2025-01-06 ~ 2025-01-13',
//       sanction_chat: '오세훈: 너 진짜 예쁘다 연락처 줄래?\n오세훈: 나이가 어떻게 되세요?',
//       add_opinion: '계속 귀찮게 해서 이벤트를 즐길 수 없었습니다.',
//       is_processed: true,
//    },
//    {
//       user_name: '서민아',
//       phone_number: '010-1111-2222',
//       reporter_name: '노승우',
//       event_name: '서울 빛초롱 축제',
//       report_date: '2025-01-05',
//       report_category: '기타',
//       sanction_content: '타인의 개인정보를 무단으로 공개했습니다.',
//       sanction_type: '미정',
//       sanction_period: '-',
//       sanction_chat: '서민아: 이 사람 전화번호는 010-xxxx-xxxx예요\n서민아: 주소는 서울시 xx구입니다',
//       add_opinion: '개인정보가 공개되어 매우 당황스러웠습니다.',
//       is_processed: false,
//    },
//    {
//       user_name: '백현우',
//       phone_number: '010-3333-4444',
//       reporter_name: '하은비',
//       event_name: '전통주 페스티벌',
//       report_date: '2025-01-04',
//       report_category: '도배',
//       sanction_content: '특수문자를 이용한 도배 행위를 했습니다.',
//       sanction_type: '7일 계정정지',
//       sanction_period: '2025-01-04 ~ 2025-01-11',
//       sanction_chat: '백현우: ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ\n백현우: !!!!!!!!!!!!!!!!!!!!',
//       add_opinion: '채팅창이 도배로 가득 차서 불편했습니다.',
//       is_processed: true,
//    },
// ];

// export const allPartyReports: PartyReportData[] = [
//    {
//       party_name: '홍대 크리스마스 마켓 투어',
//       party_chairman_name: '김철수',
//       user_name: '박지훈',
//       report_date: '2025-01-15',
//       party_dissolution_date: '2025-01-22',
//       event_name: '크리스마스 마켓',
//       sanction_content: '파티 내에서 부적절한 언어 사용 및 다른 참가자들을 불쾌하게 하는 행동이 발견되었습니다.',
//       sanction_type: '파티 해산',
//       reporter_name: '이영희',
//       report_category: '부적절한 언어',
//       add_opinion: '파티장이 여러 차례 경고를 무시했습니다.',
//       is_processed: true,
//    },
//    {
//       party_name: '성수동 팝업스토어 탐방',
//       party_chairman_name: '박민수',
//       user_name: '정다빈',
//       report_date: '2025-01-14',
//       party_dissolution_date: '-',
//       event_name: '성수동 팝업 투어',
//       sanction_content: '파티가 상업적 광고 목적으로 운영되고 있습니다.',
//       sanction_type: '미정',
//       reporter_name: '최지현',
//       report_category: '광고',
//       add_opinion: '계속해서 특정 브랜드를 홍보하고 있습니다.',
//       is_processed: false,
//    },
//    {
//       party_name: '한강 불꽃축제 관람',
//       party_chairman_name: '정수진',
//       user_name: '김도윤',
//       report_date: '2025-01-13',
//       party_dissolution_date: '2025-01-20',
//       event_name: '한강 불꽃축제',
//       sanction_content: '파티 내에서 사이비 종교 포교 활동이 진행되었습니다.',
//       sanction_type: '파티 해산',
//       reporter_name: '강민호',
//       report_category: '사이비 포교 활동',
//       add_opinion: '매우 불쾌했고 다른 참가자들도 피해를 입었습니다.',
//       is_processed: true,
//    },
//    {
//       party_name: '코엑스 푸드트럭 축제',
//       party_chairman_name: '홍길동',
//       user_name: '서지안',
//       report_date: '2025-01-12',
//       party_dissolution_date: '-',
//       event_name: '코엑스 푸드 페스티벌',
//       sanction_content: '파티 참가비를 받고 미허가 영리 활동을 진행했습니다.',
//       sanction_type: '미정',
//       reporter_name: '윤서연',
//       report_category: '미허가 영리활동',
//       add_opinion: '참가비를 환불받지 못했습니다.',
//       is_processed: false,
//    },
//    {
//       party_name: '여의도 벚꽃축제 모임',
//       party_chairman_name: '이동욱',
//       user_name: '문서윤',
//       report_date: '2025-01-11',
//       party_dissolution_date: '2025-01-18',
//       event_name: '여의도 벚꽃축제',
//       sanction_content: '파티 진행 중 불법 행위가 발생했습니다.',
//       sanction_type: '파티 해산',
//       reporter_name: '김나연',
//       report_category: '불법 행위',
//       add_opinion: '경찰에도 신고했습니다.',
//       is_processed: true,
//    },
//    {
//       party_name: 'DDP 라이트업 페스티벌',
//       party_chairman_name: '최준호',
//       user_name: '오지훈',
//       report_date: '2025-01-10',
//       party_dissolution_date: '-',
//       event_name: 'DDP 라이트업',
//       sanction_content: '공식 행사를 사칭하여 파티를 운영하고 있습니다.',
//       sanction_type: '미정',
//       reporter_name: '박서준',
//       report_category: '사칭 목적 파티',
//       add_opinion: '공식 행사인 줄 알고 참가했습니다.',
//       is_processed: false,
//    },
//    {
//       party_name: '잠실 롯데월드 할로윈 파티',
//       party_chairman_name: '강다은',
//       user_name: '김하린',
//       report_date: '2025-01-09',
//       party_dissolution_date: '2025-01-16',
//       event_name: '롯데월드 할로윈',
//       sanction_content: '파티 채팅방에서 지속적인 광고 메시지를 전송했습니다.',
//       sanction_type: '파티 해산',
//       reporter_name: '정하늘',
//       report_category: '광고',
//       add_opinion: '채팅방이 광고로 도배되어 불편했습니다.',
//       is_processed: true,
//    },
//    {
//       party_name: '광화문 광장 콘서트 관람',
//       party_chairman_name: '신예은',
//       user_name: '이준서',
//       report_date: '2025-01-08',
//       party_dissolution_date: '-',
//       event_name: '광화문 광장 콘서트',
//       sanction_content: '파티 운영 방식에 대한 불만이 제기되었습니다.',
//       sanction_type: '미정',
//       reporter_name: '조민수',
//       report_category: '기타',
//       add_opinion: '',
//       is_processed: false,
//    },
//    {
//       party_name: '명동 크래프트 맥주 페스티벌',
//       party_chairman_name: '한지우',
//       user_name: '정유나',
//       report_date: '2025-01-07',
//       party_dissolution_date: '2025-01-14',
//       event_name: '명동 맥주 페스티벌',
//       sanction_content: '파티장이 참가자들에게 부적절한 언어를 사용했습니다.',
//       sanction_type: '파티 해산',
//       reporter_name: '송유진',
//       report_category: '부적절한 언어',
//       add_opinion: '파티 분위기가 매우 불쾌했습니다.',
//       is_processed: true,
//    },
//    {
//       party_name: '이태원 월드 푸드 페스티벌',
//       party_chairman_name: '오세훈',
//       user_name: '김서연',
//       report_date: '2025-01-06',
//       party_dissolution_date: '-',
//       event_name: '이태원 푸드 페스티벌',
//       sanction_content: '상업적 목적의 광고 활동이 지속되고 있습니다.',
//       sanction_type: '미정',
//       reporter_name: '임채원',
//       report_category: '광고',
//       add_opinion: '파티가 아닌 영업 활동 같았습니다.',
//       is_processed: false,
//    },
//    {
//       party_name: '강남 K-POP 팝업스토어 투어',
//       party_chairman_name: '서민아',
//       user_name: '박현우',
//       report_date: '2025-01-05',
//       party_dissolution_date: '2025-01-12',
//       event_name: 'K-POP 팝업스토어',
//       sanction_content: '무허가로 유료 투어 프로그램을 운영했습니다.',
//       sanction_type: '파티 해산',
//       reporter_name: '노승우',
//       report_category: '미허가 영리활동',
//       add_opinion: '환불을 요청했지만 거부당했습니다.',
//       is_processed: true,
//    },
//    {
//       party_name: '서울랜드 빛축제 단체관람',
//       party_chairman_name: '백현우',
//       user_name: '윤하린',
//       report_date: '2025-01-04',
//       party_dissolution_date: '-',
//       event_name: '서울랜드 빛축제',
//       sanction_content: '파티 설명과 실제 내용이 달랐습니다.',
//       sanction_type: '미정',
//       reporter_name: '하은비',
//       report_category: '기타',
//       add_opinion: '',
//       is_processed: false,
//    },
// ];
