import Header from '@/components/header/header';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased bg-gray-50">
        {/* 여기만 추가! */}
        <Header />
        {/* 기존 children 있던 자리 그대로 두고, 왼쪽 여백만 추가 */}
        <main className="lg:pl-28 min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
