import Header from '@/components/header/header';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased bg-gray-50">
        {/* 여기만 추가! */}
        <Header />
        {/* lg:pl-20 값을 변경하면 header와 main영역 사이의 여백을 조절 가능 */}
        <main className="pl-16 lg:pl-20 min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
